[package]
name = "candi-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candi-core = { path = "../candi-core" }
candi-theme = { path = "../candi-theme" }
candi-pdf = { path = "../candi-pdf" }
crossterm = "=0.29.0"
ratatui = { version = "=0.30.2", default-features = false, features = ["crossterm"] }

[dev-dependencies]
ratatui = { version = "=0.30.2", default-features = false, features = ["crossterm"] }
